config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources 'popos'
  get '/markers'       => 'popos#map_markers'
  post '/popos/nearby' => 'popos#nearby'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/popo.rb
class Popo < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.tempfile, headers: true) do |row|
      popos = Popo.new(name: row[0],
                       lat: row[2],
                       lng: row[3],
                       restrooms: row[7],
                       address: row[1],
                       image: row[5],
                       description: row[8],
                       hours: row[10],
                       location: row[9])
      popos.save if popos.valid?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/popos_controller.rb
class PoposController < ApplicationController
  def index
    @popos = Popo.order(:id).page(params[:page])

    if request.xhr?
      render erb: :index, layout: false
    end
  end

  def create
    Popo.import(params[:file])
    redirect_to root_url
  end

  def show
    @popo = Popo.find(params[:id])
  end

  def nearby
    result = {}

    @nearby_popos = GeoService.find_nearest(user_lat: params['userLat'],
                                            user_lng: params['userLng'])

    @nearby_popos.each_with_index { |popo, i| result[i] = popo.attributes }
    result['html'] = render_to_string(:nearby, layout: false)

    render json: result
  end

  def map_markers
    @popos = Popo.all
    render json: @popos
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @popos = Popo.all.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Popos2</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= yield %>
    <main>
  </body>
</html>

app/views/popos/_nearby_popos.html.erb
<% nearby_popos.each do |popo| %>
  <div class="info-card">
    <div class="popo-list-img">
      <img src="http://sf-planning.org/ftp/files/GIS/POPOS/Pics/Small/<%= popo.image %>" onerror="this.src='http://placehold.it/250x200'" />
    </div>

    <div class="popo-list-info">
      <div class="info-card-title">
        <h1><%= popo.name %></h1>
        <%= popo.address %>
      </div>

      <p><span class="location-span"><%= popo.location %></span></p>
      <% if popo.seating %>
        <p><b>Seating: </b>Yes. <%= popo.seating_description %></p>
      <% end %>

      <% if popo.hours.length > 0 %>
        <p><b>Hours:</b> <%= popo.hours %></p>
      <% else %>
        <p><b>Hours:</b> <%= popo.hours_type %></p>
      <% end %>

      <% if popo.accessibility && popo.accessibility.length > 0 %>
        <p><b>Accessibility:</b> <%= popo.accessibility %></p>
      <% end %>

      <% if popo.description && popo.description.length > 0 %>
        <p><b>Description:</b><br><%= popo.description %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/popos/_popo_info.html.erb
<% @popos.each do |popo| %>
  <% cache popo do %>
    <div class="info-card">
      <div class="popo-list-img">
        <a href="<%= popo_path(popo) %>">
          <img src="http://sf-planning.org/ftp/files/GIS/POPOS/Pics/Small/<%= popo.image %>" onerror="this.src='http://placehold.it/250x200'" />
        </a>
      </div>

      <div class="popo-list-info">
        <div class="info-card-title">
          <h1><%= popo.name %></h1>
          <%= popo.address %>
        </div>

        <p><span class="location-span"><%= popo.location %></span></p>
        <% if popo.seating %>
          <p><b>Seating: </b>Yes. <%= popo.seating_description %></p>
        <% end %>

        <% if popo.hours.length > 0 %>
          <p><b>Hours:</b> <%= popo.hours %></p>
        <% else %>
          <p><b>Hours:</b> <%= popo.hours_type %></p>
        <% end %>

        <% if popo.accessibility && popo.accessibility.length > 0 %>
          <p><b>Accessibility:</b> <%= popo.accessibility %></p>
        <% end %>

        <% if popo.description && popo.description.length > 0 %>
          <p><b>Description:</b><br><%= popo.description %></p>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/popos/index.html.erb
<div id="list-view" style="display:none">
  <%= paginate @popos %>
  <%= render 'popo_info' %>
  <%= paginate @popos %>
</div>

app/views/popos/nearby.html.erb
<% @nearby_popos.each do |popo| %>
  <div class="info-card">
    <div class="popo-list-img">
      <a href="<%= popo_path(popo) %>">
        <img src="http://sf-planning.org/ftp/files/GIS/POPOS/Pics/Small/<%= popo.image %>" onerror="this.src='http://placehold.it/250x200'" />
      </a>
    </div>

    <div class="popo-list-info">
      <div class="info-card-title">
        <h1><%= popo.name %></h1>
        <%= popo.address %>
      </div>

      <p><span class="location-span"><%= popo.location %></span></p>
      <% if popo.seating %>
        <p><b>Seating: </b>Yes. <%= popo.seating_description %></p>
      <% end %>

      <% if popo.hours.length > 0 %>
        <p><b>Hours:</b> <%= popo.hours %></p>
      <% else %>
        <p><b>Hours:</b> <%= popo.hours_type %></p>
      <% end %>

      <% if popo.accessibility && popo.accessibility.length > 0 %>
        <p><b>Accessibility:</b> <%= popo.accessibility %></p>
      <% end %>

      <% if popo.description && popo.description.length > 0 %>
        <p><b>Description:</b><br><%= popo.description %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/popos/new.html.erb
<div class="container">
  <%= form_tag popos_path, multipart: true do %>
    <%= label_tag 'file', 'Select a file:' %>
    <%= file_field_tag 'file' %>
    <div>
      <%= button_tag 'Upload File' %>
    </div>
  <% end %>
</div>

app/views/popos/show.html.erb
<div class="container">
  <% cache(@popo) do %>
    <div class="info-card">
      <div class="popo-img">
        <img src="http://sf-planning.org/ftp/files/GIS/POPOS/Pics/Small/<%= @popo.image %>" onerror="this.src='http://placehold.it/250x200'">
      </div>

      <div class="popo-info">
        <div class="info-card-title">
          <h1><%= @popo.name %></h1>
          <%= @popo.address %>
        </div>

        <p><span class="location-span"><%= @popo.location %></span></p>
        <% if @popo.seating %>
          <p><b>Seating: </b>Yes. <%= @popo.seating_description %></p>
        <% end %>

        <% if @popo.hours.length > 0 %>
          <p><b>Hours:</b> <%= @popo.hours %></p>
        <% else %>
          <p><b>Hours:</b> <%= @popo.hours_type %></p>
        <% end %>

        <% if @popo.accessibility && @popo.accessibility.length > 0 %>
          <p><b>Accessibility:</b> <%= @popo.accessibility %></p>
        <% end %>

        <% if @popo.description && @popo.description.length > 0 %>
          <p><b>Description:</b><br><%= @popo.description %></p>
        <% end %>

      </div>
    </div>
  <% end %>
</div>

<span id="js" style="visibility:hidden">disable</span>

app/views/welcome/index.html.erb
<div class="container">
  <div class="splash">
    <div>
      <%= image_tag "POPOS.svg", class: "logo", id: "logo" %>
    </div>

    <div class="info-panel">
      <p>
        Privately-Owned Public Open Spaces (POPOS) are publicly accessible spaces in the form of plazas, terraces, atriums, small parks, and even snippets which are provided and maintained by private developers. For more information, check out the <a href="http://sf-planning.org/privately-owned-public-open-space-and-public-art-popos">SF Planning Departments' page on POPOS</a>
      </p>
    </div>

  </div>
</div>

<div id="popos-viewer">
  <div>
    <button id="view-switcher-button" class="mdl-button">view as list</button>
  </div>

  <div class="placeholder-loading">
    <i class="fa fa-circle-o-notch fa-spin fa-5x fa-fw"></i>
<span class="sr-only">Loading...</span>
  </div>

  <div id="list-view" class="container" style="display:none">
    <%= paginate @popos %>
    <%= render 'popos/popo_info' %>
    <%= paginate @popos %>
  </div>

  <div id="map-view">
    <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i>
    <span class="sr-only">Loading...</span>
  </div>
</div>

<script id="info-window-template" type="text/x-handlebars-template">
  <div class="info-window">


    <div class="popo-img">
      {{#if image}}
      <img src="http://sf-planning.org/ftp/files/GIS/POPOS/Pics/Small/{{image}}"
      onerror="this.src='http://placehold.it/200x200'"/>
      {{else}}
      <img src="http://placehold.it/200x200" />
      {{/if}}
    </div>

    <div class="popo-info">
      <div class="title">
        <h1>{{name}}
        </h1>
        {{address}}
      </div>

      <p><span class="location">{{location}}</span></p>
      {{#if seating}}
      <p><b>Seating: </b>Yes. {{seating_description}}</p>
      {{/if}}
      {{#if hours}}
      <p><b>Hours:</b> {{hours}}</p>
      {{else}}
      <p><b>Hours:</b> {{hours_type}}</p>
      {{/if}}
      {{#if accessibility}}
      <p><b>Accessibility:</b> {{accessibility}}</p>
      {{/if}}
      <p><b>Description:</b><br>{{description}}</p>
    </div>
  </div>
</script>